export const GET_SNEAKERS = "GET_SNEAKERS";
export const SEARCH_SNEAKER = "SEARCH_SNEAKER";
export const GET_DETAIL = "GET_DETAIL;";
export const FILTRO_GENERO = "FILTRO_GENERO";
export const FILTRO_MARCA = "FILTRO_MARCA";
export const SORT_BY_ALPHABET = "SORT_BY_ALPHABET";

export const FILTRO_PRECIOS = "FILTRO_PRECIOS";
export const FILTRO_CATEGORIAS = "FILTRO_CATEGORIAS";
export const GET_BRANDS = "GET_BRANDS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_GENDERS = "GET_GENDERS";
export const FILTER = "FILTER";
export const ORDEN = "ORDEN";
// DESMONTANDO DETALLE
export const DETAIL_ZERO = "DETAIL_ZERO";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
// CAMBIANDO ESTADOS - FILTROS
export const GET_ORDERS_USERS = "GET_ORDERS_USERS";
export const GET_ORDERS_ADMIN = "GET_ORDERS_ADMIN";
export const PATCH_ORDER = "PACTH_ORDER";
export const FILTER_DATE = "FILTER_DATE";
export const FILTER_STATE = "FILTER_STATE";
export const GET_USERS = "GET_USERS";
